version: 2.1
orbs:
  python: circleci/python@1.5.0

jobs:
  test: 
    docker:
      - image: cimg/python:3.10.2
      - image: cimg/redis:6.2.6
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest

workflows:
  tests:
    jobs:
      - test
